# ansible.yaml
# ansible-playbook 00-ansible.yaml -i inventory/hosts.ini --ask-become-pass
---
- hosts: development
  gather_facts: no
  become: yes
  vars_prompt:
    - name: DEFAULT_PASSWORD
      prompt: "Enter default user password"
      private: yes
      default: "password"

  roles:
    - role: ansible