## 00-prerequisites.yaml
## ansible-playbook 00-prerequisites.yaml -i inventory/hosts.ini --ask-become-pass
---
- name: Prerequisites
  hosts: development
  gather_facts: no
  become: yes
  vars_prompt:
    - name: DEFAULT_PASSWORD
      prompt: "Enter default user password"
      private: yes
      default: "password"
  roles:
    - role: prerequisites