- name: "Create directory {{ USB_MOUNT_POINT }} to mount usb stick"
  file:
    path: "{{ USB_MOUNT_POINT }}"
    state: directory

- name: Get the UUID of usb stick
  delegate_facts: true
  shell: | 
    blkid /dev/sda1 | awk -F'"' '{print $2}'
  register: uuid

- name: Mount USB stick by UUID
  ansible.posix.mount:
    src: "UUID={{ uuid.stdout }}"
    path: "{{ USB_MOUNT_POINT }}"
    fstype: ext4
    opts: rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail
    dump: 0
    passno: 2
    state: mounted

- name: Create Workspace directory on USB stick
  file:
    path: "{{ USB_MOUNT_POINT }}/Workspace"
    state: directory

- name: "Symbolic link Workspace to {{ USB_MOUNT_POINT }}"
  file:
    src: "{{ USB_MOUNT_POINT }}/Workspace"
    dest: "/home/{{ DEFAULT_USER }}/Workspace"
    owner: ian
    group: ian
    state: link