- name: Allow ansible user to execute without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ ANSIBLE_USER }}" # RegEx to check for state present
    line: "{{ ANSIBLE_USER }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Remove ansible account password login
  ansible.builtin.command: "passwd -d {{ ANSIBLE_USER }}"

- name: Add default user
  ansible.builtin.user:
    name: "{{ DEFAULT_USER }}"
    password: "{{ 'DEFAULT_PASSWORD' | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    append: yes
    groups: sudo

- name: Set authorized key for default user
  ansible.posix.authorized_key:
    user: "{{ DEFAULT_USER }}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"